[build-system]
requires = ["poetry>=1.8"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "upperroom"
description = "A website for Churches."
authors = [
    "Craig Holyoak <craig@helmsdeep.org>",
]
license = "GPL-2.0-only"
readme = "README.md"
repository = "https://github.com/thepointchurch/upperroom"
homepage = "https://github.com/thepointchurch/upperroom"
version = "3.2.0"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

exclude = [
    "**/tests.py",
    "**/tests",
]

[tool.poetry.dependencies]
python = "^3.11"

argon2-cffi = "^23.1"
bcrypt = "^4.1"
django = "~5.1"
django-csp = "^3.8"
django-environ = "~0"
django-markdownify = "~0"
django-robots = "^6.1"
mutagen = "^1.47"
weasyprint = "^63.0"
yafg = "~0"

gunicorn = "^23.0"
setproctitle = "^1.3"

cryptography = { version = "^43.0", optional = true }
django-amazon-ses = { version = "^4.0", optional = true }
django-storages = { version = "^1.14", optional = true }
botocore = { version = "^1.34", optional = true }
google-api-python-client = { version = "^2.143", optional = true }
google-auth-oauthlib = { version = "^1.2", optional = true }
psycopg = { version = "^3.1", optional = true, extras=["binary"] }
redis = { version = "^5.0", optional = true }
django-redis = { version = "^5.4", optional = true }
django-cacheops = { version = "^7.0", optional = true }

[tool.poetry.extras]
aws = [
    "cryptography",
    "django-amazon-ses",
    "django-storages",
]
cache = [
    "django-cacheops",
    "django-redis",
]
google = [
    "google-api-python-client",
    "google-auth-oauthlib",
]
pgsql = [
    "psycopg",
]

[tool.poetry.group.dev.dependencies]
coverage = "~7"
django-debug-toolbar = "~4"
gitpython = "~3"
pre-commit = "~4"
pylint = "~3"
pylint-django = "~2"
pytest = "~8"
pytest-django = "~4"
semantic_version = "~2"
tomlkit = "~0"
python-lsp-server = { version = "~1", extras=["isort", "black"] }

[tool.poetry.scripts]
upperroom = 'upperroom.commands:main'
upperroom-sendrosteremails = 'upperroom.commands:sendrosteremails'
upperroom-restore-fixtures = 'upperroom.commands:restore_fixtures'


[tool.pylint.master]
jobs = 0
load-plugins = [
    "pylint_django",
]
django-settings-module = "upperroom.settings"

[tool.pylint.format]
max-line-length = 119

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "duplicate-code",
]

[tool.pylint.variables]
ignored-argument-names = "kwargs|args"


[tool.isort]
combine_as_imports = true
include_trailing_comma = true
known_first_party = "upperroom"
line_length = 119
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true


[tool.black]
line-length = 119
include = '\.pyi?$'


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
DJANGO_SETTINGS_MODULE = "upperroom.settings"
python_files = "tests.py tests/*.py"
filterwarnings = "ignore::DeprecationWarning:yafg"


[tool.pylsp-mypy]
enabled = false
