[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "upperroom"
description = "A website for Churches."
authors = [
    "Craig Holyoak <craig@helmsdeep.org>",
]
license = "GPL-2.0-only"
readme = "README.md"
repository = "https://github.com/thepointchurch/upperroom"
homepage = "https://github.com/thepointchurch/upperroom"
version = "2.7.2"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

exclude = [
    "**/tests.py",
    "**/tests",
]

[tool.poetry.dependencies]
python = "^3.9"

argon2-cffi = "^21.3"
bcrypt = "^3.2"
django = "^3.2"
django-csp = "^3.7"
django-environ = "^0.8"
django-markwhat = "^1.6"
django-robots = "^4.0"
django-sendmail-backend = "^0.1"
mutagen = "^1.45"
weasyprint = "^53.0"
yafg = "^0.3"

gunicorn = "^20.1"
setproctitle = "^1.2"

cryptography = { version = "^36.0", optional = true }
django-amazon-ses = { version = "^4.0", optional = true }
django-storages = { version = "^1.12", optional = true }
google-api-python-client = { version = "^2.33", optional = true }
google-auth-oauthlib = { version = "^0.4", optional = true }
psycopg2 = { version = "^2.9", optional = true }
redis = { version = "^4.1", optional = true }
django-redis = { version = "^5.2", optional = true }
django-cacheops = { version = "^6.0", optional = true }

[tool.poetry.extras]
aws = [
    "cryptography",
    "django-amazon-ses",
    "django-storages",
]
cache = [
    "django-cacheops",
    "django-redis",
]
google = [
    "google-api-python-client",
    "google-auth-oauthlib",
]
pgsql = [
    "psycopg2",
]

[tool.poetry.dev-dependencies]
coverage = "^6.2"
django-debug-toolbar = "^3.2"
gitpython = "^3.1"
pre-commit = "^2.16"
pylint = "^2.12"
pylint-django = "^2.4"
pytest = "^6.2"
pytest-django = "^4.5"
semantic_version = "^2.8"
tomlkit = "^<1.0"

[tool.poetry.scripts]
upperroom = 'upperroom.commands:main'
upperroom-sendrosteremails = 'upperroom.commands:sendrosteremails'
upperroom-restore-fixtures = 'upperroom.commands:restore_fixtures'


[tool.pylint.master]
jobs = 0
load-plugins = [
    "pylint_django",
]
django-settings-module = "upperroom.settings"

[tool.pylint.format]
max-line-length = 119

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "bad-continuation",
    "bad-whitespace",
    "duplicate-code",
]

[tool.pylint.variables]
ignored-argument-names = "kwargs|args"


[tool.isort]
combine_as_imports = true
include_trailing_comma = true
known_first_party = "upperroom"
line_length = 119
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true


[tool.black]
line-length = 119
include = '\.pyi?$'


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
DJANGO_SETTINGS_MODULE = "upperroom.settings"
python_files = "tests.py tests/*.py"
filterwarnings = "ignore::django.utils.deprecation.RemovedInDjango40Warning"
