[uwsgi]
chdir = /django
module = upperroom.wsgi
home = /django/.venv
module = upperroom.wsgi
socket = :8000

master = true
vacuum = true

if-env = UWSGI_PROCESSES
processes = %(_)
endif =
if-env = UWSGI_THREADS
enable-threads = true
threads = %(_)
endif =
if-env = UWSGI_QUEUE
listen = %(_)
endif =

log-x-forwarded-for = true
