# Generated by Django 2.1.4 on 2019-05-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_podcasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefeed',
            name='show_children',
            field=models.BooleanField(default=False, verbose_name='show children'),
        ),
    ]
