#!/bin/sh

BUCKET='thepoint-logs'

if [ -d "/opt/python/bin" ] ; then
    PATH="/opt/python/bin:$PATH"
fi

aws s3 sync /var/log/django/ "s3://${BUCKET}/django" --exclude=*.log --quiet
aws s3 sync /var/log/nginx/ "s3://${BUCKET}/nginx" --exclude=*.log --quiet
